alias GreenManTavern.Repo
alias GreenManTavern.Systems.System

systems = [
  # FOOD PRODUCTION SYSTEMS (15+)
  %{
    name: "Herb Garden",
    system_type: "resource",
    category: "food",
    description: "Indoor or outdoor herbs for cooking and medicine",
    requirements: "Containers or garden bed, soil, sunlight",
    default_inputs: ["water", "sunlight", "nutrients"],
    default_outputs: ["fresh-herbs", "plant-waste"],
    icon_name: "Leaf",
    space_required: "indoor,outdoor,balcony",
    skill_level: "beginner",
    color_scheme: "#CCCCCC"
  },
  %{
    name: "Vegetable Garden",
    system_type: "resource",
    category: "food",
    description: "Annual vegetables for fresh consumption",
    requirements: "Garden bed, soil, seeds, water",
    default_inputs: ["water", "sunlight", "compost", "seeds"],
    default_outputs: ["vegetables", "plant-waste"],
    icon_name: "Sprout",
    space_required: "outdoor,yard",
    skill_level: "beginner",
    color_scheme: "#BBBBBB"
  },
  %{
    name: "Fruit Trees",
    system_type: "resource",
    category: "food",
    description: "Perennial fruit trees for long-term harvest",
    requirements: "Space for tree, soil, pruning tools",
    default_inputs: ["water", "sunlight", "nutrients"],
    default_outputs: ["fruit", "leaves", "wood"],
    icon_name: "TreeDeciduous",
    space_required: "outdoor,yard",
    skill_level: "intermediate",
    color_scheme: "#AAAAAA"
  },
  %{
    name: "Berry Bushes",
    system_type: "resource",
    category: "food",
    description: "Small fruit bushes for berries",
    requirements: "Space for bushes, soil, netting",
    default_inputs: ["water", "sunlight", "nutrients"],
    default_outputs: ["berries", "leaves"],
    icon_name: "Cherry",
    space_required: "outdoor,yard",
    skill_level: "beginner",
    color_scheme: "#999999"
  },
  %{
    name: "Windowsill Sprouts",
    system_type: "resource",
    category: "food",
    description: "Microgreens grown on windowsill",
    requirements: "Shallow containers, seeds, water",
    default_inputs: ["water", "sunlight", "seeds"],
    default_outputs: ["microgreens", "seed-hulls"],
    icon_name: "Sun",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#DDDDDD"
  },
  %{
    name: "Indoor Microgreens",
    system_type: "resource",
    category: "food",
    description: "High-nutrient microgreens grown indoors",
    requirements: "Growing trays, seeds, grow lights",
    default_inputs: ["water", "light", "seeds"],
    default_outputs: ["microgreens", "seed-hulls"],
    icon_name: "Sun",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#EEEEEE"
  },
  %{
    name: "Container Garden",
    system_type: "resource",
    category: "food",
    description: "Vegetables grown in containers",
    requirements: "Pots, soil, drainage",
    default_inputs: ["water", "sunlight", "nutrients"],
    default_outputs: ["vegetables", "plant-waste"],
    icon_name: "Container",
    space_required: "outdoor,balcony",
    skill_level: "beginner",
    color_scheme: "#CCCCCC"
  },
  %{
    name: "Greenhouse",
    system_type: "resource",
    category: "food",
    description: "Controlled environment for year-round growing",
    requirements: "Greenhouse structure, heating, ventilation",
    default_inputs: ["water", "light", "heat"],
    default_outputs: ["vegetables", "herbs", "plant-waste"],
    icon_name: "Sun",
    space_required: "outdoor,yard",
    skill_level: "advanced",
    color_scheme: "#AAAAAA"
  },
  %{
    name: "Raised Beds",
    system_type: "resource",
    category: "food",
    description: "Elevated growing beds for better drainage",
    requirements: "Wood/concrete frames, soil, compost",
    default_inputs: ["water", "sunlight", "compost"],
    default_outputs: ["vegetables", "plant-waste"],
    icon_name: "Square",
    space_required: "outdoor,yard",
    skill_level: "intermediate",
    color_scheme: "#BBBBBB"
  },
  %{
    name: "Vertical Garden",
    system_type: "resource",
    category: "food",
    description: "Space-efficient vertical growing system",
    requirements: "Vertical structure, containers, irrigation",
    default_inputs: ["water", "sunlight", "nutrients"],
    default_outputs: ["herbs", "vegetables", "plant-waste"],
    icon_name: "ArrowUp",
    space_required: "outdoor,balcony",
    skill_level: "intermediate",
    color_scheme: "#999999"
  },
  %{
    name: "Aquaponics",
    system_type: "resource",
    category: "food",
    description: "Fish and plants in symbiotic system",
    requirements: "Fish tank, grow beds, pump, fish",
    default_inputs: ["fish-food", "water", "light"],
    default_outputs: ["fish", "vegetables", "fish-waste"],
    icon_name: "Fish",
    space_required: "outdoor,indoor",
    skill_level: "advanced",
    color_scheme: "#888888"
  },
  %{
    name: "Hydroponics",
    system_type: "resource",
    category: "food",
    description: "Soilless growing with nutrient solution",
    requirements: "Growing medium, nutrient solution, pump",
    default_inputs: ["water", "nutrients", "light"],
    default_outputs: ["vegetables", "herbs", "plant-waste"],
    icon_name: "Droplets",
    space_required: "indoor,outdoor",
    skill_level: "advanced",
    color_scheme: "#777777"
  },
  %{
    name: "Mushroom Cultivation",
    system_type: "resource",
    category: "food",
    description: "Growing mushrooms on substrate",
    requirements: "Substrate, spores, humidity control",
    default_inputs: ["substrate", "water", "spores"],
    default_outputs: ["mushrooms", "spent-substrate"],
    icon_name: "Circle",
    space_required: "indoor,outdoor",
    skill_level: "intermediate",
    color_scheme: "#666666"
  },
  %{
    name: "Seed Saving",
    system_type: "resource",
    category: "food",
    description: "Collecting and storing seeds for future planting",
    requirements: "Mature plants, storage containers",
    default_inputs: ["mature-plants", "flowers"],
    default_outputs: ["seeds", "plant-waste"],
    icon_name: "Archive",
    space_required: "indoor,outdoor",
    skill_level: "intermediate",
    color_scheme: "#555555"
  },
  %{
    name: "Perennial Vegetables",
    system_type: "resource",
    category: "food",
    description: "Long-lived vegetables that return each year",
    requirements: "Space for perennials, soil preparation",
    default_inputs: ["water", "sunlight", "nutrients"],
    default_outputs: ["vegetables", "leaves", "plant-waste"],
    icon_name: "TreePine",
    space_required: "outdoor,yard",
    skill_level: "intermediate",
    color_scheme: "#444444"
  },

  # PROCESSING SYSTEMS (12+)
  %{
    name: "Composting",
    system_type: "process",
    category: "waste",
    description: "Turn organic waste into rich soil amendment",
    requirements: "Bin/tumbler/pile, browns and greens",
    default_inputs: ["food-scraps", "plant-waste", "browns"],
    default_outputs: ["compost"],
    icon_name: "TreeDeciduous",
    space_required: "outdoor,balcony",
    skill_level: "beginner",
    color_scheme: "#999999"
  },
  %{
    name: "Drying/Dehydrating",
    system_type: "process",
    category: "food",
    description: "Preserve food by removing moisture",
    requirements: "Dehydrator or drying racks, heat source",
    default_inputs: ["fresh-food", "heat"],
    default_outputs: ["dried-food"],
    icon_name: "Sun",
    space_required: "indoor,outdoor",
    skill_level: "beginner",
    color_scheme: "#CCCCCC"
  },
  %{
    name: "Fermenting",
    system_type: "process",
    category: "food",
    description: "Preserve food through beneficial bacteria",
    requirements: "Fermentation vessels, salt, starter culture",
    default_inputs: ["fresh-food", "salt", "water"],
    default_outputs: ["fermented-food", "brine"],
    icon_name: "Zap",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#BBBBBB"
  },
  %{
    name: "Canning",
    system_type: "process",
    category: "food",
    description: "Preserve food in sealed jars",
    requirements: "Jars, lids, canner, heat source",
    default_inputs: ["fresh-food", "heat", "jars"],
    default_outputs: ["canned-food"],
    icon_name: "Container",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#AAAAAA"
  },
  %{
    name: "Worm Bin",
    system_type: "process",
    category: "waste",
    description: "Composting with worms for faster breakdown",
    requirements: "Bin, bedding, worms, food scraps",
    default_inputs: ["food-scraps", "bedding"],
    default_outputs: ["worm-castings", "worms"],
    icon_name: "Bug",
    space_required: "indoor,outdoor",
    skill_level: "intermediate",
    color_scheme: "#999999"
  },
  %{
    name: "Bokashi",
    system_type: "process",
    category: "waste",
    description: "Anaerobic fermentation of food waste",
    requirements: "Bokashi bran, airtight container",
    default_inputs: ["food-scraps", "bokashi-bran"],
    default_outputs: ["bokashi-compost"],
    icon_name: "Zap",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#888888"
  },
  %{
    name: "Herb Processing",
    system_type: "process",
    category: "food",
    description: "Dry and process herbs for storage",
    requirements: "Drying racks, storage containers",
    default_inputs: ["fresh-herbs", "heat"],
    default_outputs: ["dried-herbs", "herb-oils"],
    icon_name: "Leaf",
    space_required: "indoor,outdoor",
    skill_level: "beginner",
    color_scheme: "#777777"
  },
  %{
    name: "Water Filtration",
    system_type: "process",
    category: "water",
    description: "Clean water through natural filtration",
    requirements: "Sand, gravel, charcoal, containers",
    default_inputs: ["dirty-water"],
    default_outputs: ["clean-water", "filter-waste"],
    icon_name: "Droplets",
    space_required: "outdoor,indoor",
    skill_level: "intermediate",
    color_scheme: "#666666"
  },
  %{
    name: "Solar Dehydrator",
    system_type: "process",
    category: "food",
    description: "Use solar energy to dry food",
    requirements: "Solar collector, drying chamber, ventilation",
    default_inputs: ["fresh-food", "sunlight"],
    default_outputs: ["dried-food"],
    icon_name: "Sun",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#555555"
  },
  %{
    name: "Cold Storage",
    system_type: "process",
    category: "food",
    description: "Store food at cool temperatures",
    requirements: "Cool, dark space, ventilation",
    default_inputs: ["fresh-food"],
    default_outputs: ["stored-food"],
    icon_name: "Snowflake",
    space_required: "indoor,outdoor",
    skill_level: "beginner",
    color_scheme: "#444444"
  },
  %{
    name: "Oil Extraction",
    system_type: "process",
    category: "food",
    description: "Extract oils from seeds and nuts",
    requirements: "Press or mortar, seeds/nuts",
    default_inputs: ["seeds", "nuts"],
    default_outputs: ["oil", "meal"],
    icon_name: "Droplets",
    space_required: "indoor",
    skill_level: "advanced",
    color_scheme: "#333333"
  },
  %{
    name: "Grain Processing",
    system_type: "process",
    category: "food",
    description: "Process grains for consumption",
    requirements: "Mill, storage containers",
    default_inputs: ["grains"],
    default_outputs: ["flour", "bran"],
    icon_name: "Circle",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#222222"
  },

  # STORAGE SYSTEMS (8+)
  %{
    name: "Kitchen",
    system_type: "storage",
    category: "food",
    description: "Central food preparation and consumption area",
    requirements: "Standard kitchen facilities",
    default_inputs: ["fresh-herbs", "vegetables", "preserved-foods"],
    default_outputs: ["food-scraps", "meals"],
    icon_name: "Container",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#DDDDDD"
  },
  %{
    name: "Pantry",
    system_type: "storage",
    category: "food",
    description: "Dry food storage area",
    requirements: "Cool, dry space, shelves",
    default_inputs: ["dried-foods", "canned-foods"],
    default_outputs: ["stored-foods"],
    icon_name: "Archive",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#CCCCCC"
  },
  %{
    name: "Spice Rack",
    system_type: "storage",
    category: "food",
    description: "Organized storage for herbs and spices",
    requirements: "Shelving, containers",
    default_inputs: ["dried-herbs", "spices"],
    default_outputs: ["seasoned-foods"],
    icon_name: "Leaf",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#BBBBBB"
  },
  %{
    name: "Root Cellar",
    system_type: "storage",
    category: "food",
    description: "Underground storage for root vegetables",
    requirements: "Underground space, ventilation",
    default_inputs: ["root-vegetables"],
    default_outputs: ["stored-vegetables"],
    icon_name: "Archive",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#AAAAAA"
  },
  %{
    name: "Refrigerator",
    system_type: "storage",
    category: "food",
    description: "Cold storage for perishable foods",
    requirements: "Refrigeration unit, electricity",
    default_inputs: ["perishable-foods"],
    default_outputs: ["chilled-foods"],
    icon_name: "Snowflake",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#999999"
  },
  %{
    name: "Freezer",
    system_type: "storage",
    category: "food",
    description: "Frozen storage for long-term preservation",
    requirements: "Freezer unit, electricity",
    default_inputs: ["food-to-freeze"],
    default_outputs: ["frozen-foods"],
    icon_name: "Snowflake",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#888888"
  },
  %{
    name: "Seed Bank",
    system_type: "storage",
    category: "food",
    description: "Long-term storage for seeds",
    requirements: "Cool, dry containers, labels",
    default_inputs: ["seeds"],
    default_outputs: ["stored-seeds"],
    icon_name: "Archive",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#777777"
  },
  %{
    name: "Preserve Jars",
    system_type: "storage",
    category: "food",
    description: "Storage for canned and preserved foods",
    requirements: "Jars, lids, storage space",
    default_inputs: ["canned-foods", "preserves"],
    default_outputs: ["stored-preserves"],
    icon_name: "Container",
    space_required: "indoor",
    skill_level: "beginner",
    color_scheme: "#666666"
  },

  # WATER SYSTEMS (8+)
  %{
    name: "Rain Collection",
    system_type: "resource",
    category: "water",
    description: "Collect rainwater for irrigation and use",
    requirements: "Collection surface, storage tank, gutters",
    default_inputs: ["rainwater"],
    default_outputs: ["stored-water"],
    icon_name: "Droplets",
    space_required: "outdoor",
    skill_level: "beginner",
    color_scheme: "#CCCCCC"
  },
  %{
    name: "Water Tank",
    system_type: "storage",
    category: "water",
    description: "Storage for collected water",
    requirements: "Tank, pump, filtration",
    default_inputs: ["collected-water"],
    default_outputs: ["stored-water"],
    icon_name: "Container",
    space_required: "outdoor",
    skill_level: "intermediate",
    color_scheme: "#BBBBBB"
  },
  %{
    name: "Greywater System",
    system_type: "process",
    category: "water",
    description: "Reuse household greywater for irrigation",
    requirements: "Collection system, filtration, distribution",
    default_inputs: ["greywater"],
    default_outputs: ["irrigation-water"],
    icon_name: "Droplets",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#AAAAAA"
  },
  %{
    name: "Irrigation",
    system_type: "process",
    category: "water",
    description: "Distribute water to plants efficiently",
    requirements: "Pipes, emitters, timer",
    default_inputs: ["water"],
    default_outputs: ["irrigated-plants"],
    icon_name: "Droplets",
    space_required: "outdoor",
    skill_level: "intermediate",
    color_scheme: "#999999"
  },
  %{
    name: "Pond",
    system_type: "resource",
    category: "water",
    description: "Natural water feature for ecosystem support",
    requirements: "Excavation, liner, plants, fish",
    default_inputs: ["water", "nutrients"],
    default_outputs: ["fish", "aquatic-plants", "water"],
    icon_name: "Circle",
    space_required: "outdoor,yard",
    skill_level: "advanced",
    color_scheme: "#888888"
  },
  %{
    name: "Swale",
    system_type: "process",
    category: "water",
    description: "Contour trench to slow and spread water",
    requirements: "Excavation, contour following",
    default_inputs: ["rainwater", "runoff"],
    default_outputs: ["infiltrated-water"],
    icon_name: "ArrowDown",
    space_required: "outdoor,yard",
    skill_level: "advanced",
    color_scheme: "#777777"
  },
  %{
    name: "Water Barrel",
    system_type: "storage",
    category: "water",
    description: "Small-scale rainwater storage",
    requirements: "Barrel, spigot, overflow",
    default_inputs: ["rainwater"],
    default_outputs: ["stored-water"],
    icon_name: "Container",
    space_required: "outdoor,balcony",
    skill_level: "beginner",
    color_scheme: "#666666"
  },
  %{
    name: "Drip Irrigation",
    system_type: "process",
    category: "water",
    description: "Precise water delivery to plant roots",
    requirements: "Drip lines, emitters, timer",
    default_inputs: ["water"],
    default_outputs: ["irrigated-plants"],
    icon_name: "Droplets",
    space_required: "outdoor",
    skill_level: "intermediate",
    color_scheme: "#555555"
  },

  # ENERGY SYSTEMS (7+)
  %{
    name: "Solar Dehydrator",
    system_type: "process",
    category: "energy",
    description: "Use solar energy to dry food",
    requirements: "Solar collector, drying chamber",
    default_inputs: ["sunlight", "fresh-food"],
    default_outputs: ["dried-food"],
    icon_name: "Sun",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#CCCCCC"
  },
  %{
    name: "Passive Solar Design",
    system_type: "resource",
    category: "energy",
    description: "Design buildings to capture solar heat",
    requirements: "South-facing windows, thermal mass",
    default_inputs: ["sunlight"],
    default_outputs: ["heat"],
    icon_name: "Sun",
    space_required: "indoor,outdoor",
    skill_level: "advanced",
    color_scheme: "#BBBBBB"
  },
  %{
    name: "Thermal Mass",
    system_type: "storage",
    category: "energy",
    description: "Store heat in dense materials",
    requirements: "Stone, concrete, water containers",
    default_inputs: ["heat"],
    default_outputs: ["stored-heat"],
    icon_name: "Square",
    space_required: "indoor,outdoor",
    skill_level: "intermediate",
    color_scheme: "#AAAAAA"
  },
  %{
    name: "Solar Panels",
    system_type: "resource",
    category: "energy",
    description: "Convert sunlight to electricity",
    requirements: "Panels, inverter, mounting system",
    default_inputs: ["sunlight"],
    default_outputs: ["electricity"],
    icon_name: "Sun",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#999999"
  },
  %{
    name: "Wind Power",
    system_type: "resource",
    category: "energy",
    description: "Generate electricity from wind",
    requirements: "Wind turbine, inverter, mounting",
    default_inputs: ["wind"],
    default_outputs: ["electricity"],
    icon_name: "Wind",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#888888"
  },
  %{
    name: "Biogas Digester",
    system_type: "process",
    category: "energy",
    description: "Convert organic waste to methane gas",
    requirements: "Digester tank, gas collection system",
    default_inputs: ["organic-waste"],
    default_outputs: ["methane", "digestate"],
    icon_name: "Zap",
    space_required: "outdoor",
    skill_level: "advanced",
    color_scheme: "#777777"
  },
  %{
    name: "Wood Stove",
    system_type: "process",
    category: "energy",
    description: "Burn wood for heating and cooking",
    requirements: "Stove, chimney, wood supply",
    default_inputs: ["wood"],
    default_outputs: ["heat", "ash"],
    icon_name: "Flame",
    space_required: "indoor",
    skill_level: "intermediate",
    color_scheme: "#666666"
  }
]

# Insert all systems
Enum.each(systems, fn system_data ->
  %System{}
  |> System.changeset(system_data)
  |> Repo.insert!()
end)

IO.puts("Seeded #{length(systems)} permaculture systems")
