import Config

# Configure your database
config :green_man_tavern, GreenManTavern.Repo,
  username: "jesse",
  password: System.get_env("DATABASE_PASSWORD", "jesse"),
  hostname: "localhost",
  database: "green_man_tavern_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :green_man_tavern, GreenManTavernWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    System.get_env(
      "SECRET_KEY_BASE",
      "2jT4fSivaSbnqHr6+sf/mOxfFgUqNsvdKdarts2Rf++sTrpYgXWeF6oW1g4i1rTf"
    ),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:green_man_tavern, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:green_man_tavern, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :green_man_tavern, GreenManTavernWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/green_man_tavern_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :green_man_tavern, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# MindsDB Configuration for Development
# This configuration provides connection settings for MindsDB integration
# in the development environment. MindsDB is an AI database that enables
# natural language queries and machine learning model training.
config :green_man_tavern, GreenManTavern.MindsDB,
  # Host address where MindsDB server is running
  # Default: localhost (MindsDB running locally via Docker)
  host: "localhost",

  # HTTP API port for MindsDB REST endpoints
  # This is used for querying agents and models via HTTP requests
  # Default: 48334 (MindsDB's Docker container HTTP API port)
  http_port: 48334,

  # MySQL-compatible port for direct database connections
  # This port allows SQL queries to be executed directly against MindsDB
  # Default: 48335 (MindsDB's Docker container MySQL-compatible port)
  mysql_port: 48335,

  # Database name within MindsDB instance
  # MindsDB uses this database to store models, agents, and data sources
  database: "mindsdb",

  # Username for MindsDB authentication
  # Default MindsDB installation uses 'mindsdb' as username
  username: "mindsdb",

  # Password for MindsDB authentication
  # Default MindsDB installation has empty password
  password: "",

  # Connection pool size for managing concurrent database connections
  # Higher values allow more concurrent queries but use more memory
  # Development uses smaller pool to conserve resources
  pool_size: 5
