import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :green_man_tavern, GreenManTavernWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# MindsDB HTTP API configuration for Production
config :green_man_tavern,
  mindsdb_host: System.get_env("MINDSDB_HOST", "localhost"),
  mindsdb_http_port: String.to_integer(System.get_env("MINDSDB_HTTP_PORT", "47334")),
  mindsdb_user: System.get_env("MINDSDB_USER", "mindsdb"),
  mindsdb_password: System.get_env("MINDSDB_PASSWORD", "mindsdb")

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
